import '../styles/globals.css'
import { Carme } from 'next/font/google'
import { Header } from './components/Header'

const carme = Carme({ subsets: ['latin'], weight: '400', variable: "--font-carme" })

export const metadata = {
  title: 'Albert Toll 3D Artist',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={carme.className}>
        <Header />
        {children}</body >
    </html >
  )
}
