import { register } from 'swiper/element/bundle';
import { Carme } from 'next/font/google'
import '../styles/globals.css'
import { ThemeProvider } from './utils/ThemeContext';
register();

import Navigation from './components/Navigation'
import { Frame } from './components/layout-utils/layout-utils'

const carme = Carme({ subsets: ['latin'], weight: '400', variable: "--font-carme" })

export const metadata = {
  title: 'Albert Toll 3D Artist',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`relative w-full ${carme.className}`}>
        <ThemeProvider>
          <header className="fixed top-0 left-0 right-0 px-df pt-df w-full z-30">
            <Navigation />
          </header>
          {children}
          <Frame />
        </ThemeProvider>
      </body >
    </html >
  )
}
