/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF, PerspectiveCamera } from "@react-three/drei"

export function Capsule({props}) {
    const { nodes, materials } = useGLTF("/capsule_corp_night.gltf")

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Cylinder001.geometry}
                material={materials.floor}
                position={[36.773, 0.001, -13.849]}
                rotation={[Math.PI / 2, 0, 2.781]}
            />
            <PerspectiveCamera
                makeDefault={true}
                far={100}
                near={0.1}
                fov={22.895}
                position={[12.072, 4.284, -7.668]}
                rotation={[-2.833, 0.893, 2.898]}
            />
            <group position={[1.5, 0, 3]} scale={2}>
                <group position={[0.006, 0, 0]} scale={0.965}>
                    <mesh
                        geometry={nodes.Sphere002_1.geometry}
                        material={materials.marquesina}
                    />
                    <mesh
                        geometry={nodes.Sphere002_2.geometry}
                        material={materials.column}
                    />
                </group>
                <mesh
                    geometry={nodes.Cylinder.geometry}
                    material={materials.walls}
                    position={[0.089, 0, -0.055]}
                    scale={0.898}
                />
                <pointLight
                    intensity={90}
                    decay={2}
                    color="#70b8ff"
                    position={[6.294, 8.735, -1.005]}
                    rotation={[-1.839, 0.602, 1.932]}
                />
                <pointLight
                    intensity={0.5}
                    decay={2}
                    color="#ffe6bb"
                    position={[1.024, 0.107, 0.003]}
                    rotation={[-1.839, 0.602, 1.932]}
                />
                <pointLight
                    intensity={0.5}
                    decay={2}
                    color="#e2d8ff"
                    position={[-8.95, 9.927, -5.843]}
                    rotation={[-1.839, 0.602, 1.932]}
                />
                <pointLight
                    intensity={0.5}
                    decay={2}
                    color="#c0f5ff"
                    position={[-3.962, 1.658, -4.511]}
                    rotation={[-1.839, 0.602, 1.932]}
                />
                <mesh
                    geometry={nodes.Sphere003_1.geometry}
                    material={materials.walls}
                />
                <mesh
                    geometry={nodes.Sphere003_2.geometry}
                    material={materials.window}
                />
                <mesh geometry={nodes.Sphere003_3.geometry} material={materials.door} />
                <mesh geometry={nodes.Sphere003_4.geometry} material={materials.roof} />
                <mesh geometry={nodes.Sphere004.geometry} material={materials.walls} />
                <mesh geometry={nodes.Sphere004_1.geometry} material={materials.roof} />
                <mesh
                    geometry={nodes.Sphere004_2.geometry}
                    material={materials.window}
                />
            </group>
        </group>
    )
}

useGLTF.preload("/capsule_corp_night.gltf")
